esphome:
  project:
    name: topi314.Fridge
    version: 2025.4.0
  name: fridge
  friendly_name: Fridge
  name_add_mac_suffix: true
  min_version: 2025.3.3

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: debug
  logs:
    sensor: WARN # avoids logging debug sensor updates

one_wire:
  - platform: gpio
    pin: GPIO4

sensor:
  # yellow
  - platform: dallas_temp
    address: ${temperature_1}
    name: "Temperature 1"
    update_interval: 15s
    # red
  - platform: dallas_temp
    address: ${temperature_2}
    name: "Temperature 2"
    update_interval: 15s
